### ISSUE TITLE
"Unable to determine a suitable packaging system type" - Fedora

### ISSUE THREAD

**Issue by mariuszs** [fsfe/reuse-tool#425] opened 2021-10-18 12:24 UTC
```reuse --lint
Traceback (most recent call last):
  File "/usr/bin/reuse", line 33, in <module>
    sys.exit(load_entry_point('reuse==0.12.1', 'console_scripts', 'reuse')())
  File "/usr/bin/reuse", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/reuse/_main.py", line 14, in <module>
    from . import (
  File "/usr/lib/python3.10/site-packages/reuse/download.py", line 17, in <module>
    from ._util import (
  File "/usr/lib/python3.10/site-packages/reuse/_util.py", line 26, in <module>
    from debian.copyright import Copyright
  File "/usr/lib/python3.10/site-packages/debian/copyright.py", line 54, in <module>
    from debian import deb822
  File "/usr/lib/python3.10/site-packages/debian/deb822.py", line 283, in <module>
    import debian.debian_support
  File "/usr/lib/python3.10/site-packages/debian/debian_support.py", line 46, in <module>
    apt_pkg.init()
apt_pkg.Error: W:Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory), E:Unable to determine a suitable packaging system type

**Comment by mxmehl** [comment] 2021-10-18 13:04
Could you please share which repo you are working on, and which command triggered the error? Also, the OS you're using and how you installed the tool would be helpful.

From the output I can only see that there is some issue with python-debian, a dependency of this tool.

**Comment by seabass-labrax** [comment] 2021-10-18 14:30
I can't reproduce the error with Fedora 31, reuse 0.13.0 python-debian 0.1.42. Given that, I presume that either python-debian fails with more recent versions of Fedora, or that there is some difference between the versions of reuse and python-debian that I installed from PyPi and the ones packaged in Fedora.

**Comment by Jayman2000** [comment] 2021-11-05 18:57
You can work around this by installing reuse with pip. See <https://bugzilla.redhat.com/show_bug.cgi?id=2003456>.

**Comment by seabass-labrax** [comment] 2021-11-25 12:43
I have an update on this! With help from the `python-debian` developers, I've identified the source of the error. It occurs due to the presence of `python3-apt`, which is a 'recommended' dependency in the Fedora package for `python-debian`.

If `python3-apt` is present, `python-debian` also expects a valid APT configuration directory, which clearly does not exist on a typical Fedora system!

@Conan-Kudo added the recommended dependency in Fedora, but told me that even that was a compromise for other users who _do_ actually use APT on Fedora (!), so it can't just be removed. As of yesterday I now have a Debian Salsa account though, so I'll be sending a pull request upstream to make `python-debian` more resilient to the absence of an APT configuration directory. That should hopefully resolve the issue! :)

**Comment by mxmehl** [comment] 2021-11-25 18:30
Excellent, thanks for following up on this @seabass-labrax! Let's hope this loophole will be closed soon for Fedora users.

**Comment by txt-file** [comment] 2021-12-28 12:51
This bug just bit me. I installed reuse via `python3 -m pip install --upgrade --user reuse`.
* reuse is version 0.14.0
* python-debian is version 0.1.36

**Comment by mxmehl** [comment] 2021-12-29 10:55
Can we (reuse-tool) do something about it, or is it really just dependent on python-debian?

**Comment by Ian2020** [comment] 2022-06-16 14:45
This now works for me on Fedora 35, reuse version 0.13 and appears to have been backported to Fedora 34 also. Fixes were submitted about 5 months ago to fix the root cause: https://bugzilla.redhat.com/show_bug.cgi?id=2014636.

**Comment by mxmehl** [comment] 2022-07-26 12:47
Good to know, thank you! I am closing this error then. We have a more general issue on retiring python-debian.

**Closed by mxmehl** 2022-07-26 12:47 UTC
Labels: bug, upstream
