### ISSUE TITLE
Generated SPDX version is out of date

### ISSUE THREAD

**Issue by anthonyharrison** [fsfe/reuse-tool#639] opened 2022-12-21 22:30 UTC
The generated SPDX file is reported as version SPDX-2.1. The latest version is SPDX-2.3. 

Using the [SPDX Python Tools package](https://github.com/spdx/tools-python) should be used to ensure the tool stays aligned with the latest SPDX standard.

**Comment by mxmehl** [comment] 2023-01-04 16:41
Yes. But it's a duplicate of #394

**Closed by mxmehl** 2023-01-04 16:41 UTC
