### ISSUE TITLE
Add prefer multi line option to reuse annotate

### ISSUE THREAD

**Issue by nea89o** [fsfe/reuse-tool#916] opened 2024-02-17 12:35 UTC
Right now `reuse annotate` prefers single line comments and falls back to multi line comments where single line comments are not available. Multi line comments can be forced using `--multi-line`. Sadly this will break if a file does not support multi line comments (it does not fall back to single line comments). I would love for there to be a `reuse annotate` flag that has that fall back to single line comment behaviour.

**Comment by carmenbianca** [comment] 2024-02-19 13:59
Duplicate of #914 :)

Thanks for opening an issue!

**Closed by carmenbianca** 2024-02-19 13:59 UTC
