### ISSUE TITLE
Installing on windows 3.9 causes exception on run

### ISSUE THREAD

**Issue by HurricanKai** [fsfe/reuse-tool#356] opened 2021-05-07 13:44 UTC
So I just installed this - updated my python installation to 3.9, updated pip, then ran `pip3 install --user reuse` in a terminal. Added the scripts dir to my PATH.
Running simply `reuse` causes
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\reuse.exe\__main__.py", line 4, in <module>
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\reuse\_main.py", line 14, in <module>
    from . import (
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\reuse\download.py", line 17, in <module>
    from ._util import (
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\reuse\_util.py", line 26, in <module>
    from debian.copyright import Copyright
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\debian\copyright.py", line 59, in <module>
    from debian import deb822
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\debian\deb822.py", line 321, in <module>
    import debian.changelog
  File "C:\Users\kaije\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\debian\changelog.py", line 93, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```
The same happens when running `reuse lint`.

Luckily running from within WSL seems to work.

**Comment by mxmehl** [comment] 2021-05-12 10:57
Seems to be a duplicate of #322, which is a problem of python-debian.

**Closed by mxmehl** 2021-05-12 10:57 UTC

**Comment by marcoXbresciani** [comment] 2021-05-28 14:44
Only a mention to the installation procedure for python-debian "previous version".
I'm absolutely ignorant of Python, add to search for it: I hope this note will help other users: I've moved back from python-debian 0.1.39 (already installed) to 0.1.38 using `pip3 install -Iv --user python-debian==0.1.38` on Windows 10 Enterprise, Command Prompt with Python 3.9.5.
