### ISSUE TITLE
Odd output for SPDX-FileCopyrightText in .license-file when creating spdx

### ISSUE THREAD

**Issue by steffenb7333** [fsfe/reuse-tool#571] opened 2022-08-17 09:02 UTC
file.license:
```
SPDX-FileCopyrightText: STRING
SPDX-License-Identifier: CC0-1.0
```

The output for `reuse spdx` is then
```
FileName: file
...
FileCopyrightText: <text>SPDX-FileCopyrightText: STRING</text>
```

The repetition of `SPDX-FileCopyrightText:` feels oddly redundant and IMHO it should only say `<text>STRING</text>`.

**Comment by mxmehl** [comment] 2022-08-18 08:06
Duplicate of #536

**Closed by mxmehl** 2022-08-18 08:06 UTC
Labels: duplicate
