### ISSUE TITLE
reuse deletes more than just old copyright information

### ISSUE THREAD

**Issue by jonasstein** [fsfe/reuse-tool#577] opened 2022-08-24 10:08 UTC
The catch2 testing framework uses:

```
/*
 *  Catch v2.13.9
 *  Generated: 2022-04-12 22:37:23.260201
 *  ----------------------------------------------------------
 *  This file has been merged from multiple headers. Please don't edit it directly
 *  Copyright (c) 2022 Two Blue Cubes Ltd. All rights reserved.
 *
 *  Distributed under the Boost Software License, Version 1.0. (See accompanying
 *  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */
#ifndef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
#define TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
// start catch.hpp

```

`reuse addheader --copyright="Two Blue Cubes Ltd. All rights reserved." --license=BSL-1.0  --year=2022 catch.hpp`

changes this to

```
// Copyright (c) 2022 Two Blue Cubes Ltd. All rights reserved.
// SPDX-FileCopyrightText: 2022 Two Blue Cubes Ltd. All rights reserved.
//
// SPDX-License-Identifier: BSL-1.0

#ifndef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
#define TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
// start catch.hpp
```

and deleted too much. 

Perhaps related to: https://github.com/fsfe/reuse-tool/pull/560

**Comment by mxmehl** [comment] 2022-08-24 12:59
It's rather related to #550 and a duplicate of #338. It's known and it's likely to be possible to circumvent this in the next release :)

**Closed by mxmehl** 2022-08-24 12:59 UTC
