### ISSUE TITLE
Missing end-of-line in `addheader` generated license

### ISSUE THREAD

**Issue by vanrein** [fsfe/reuse-tool#279] opened 2020-12-03 07:03 UTC
When I asked `reuse addheader` to attach a header to a `.png`, it produced a `.png.license` with a strange format:

  * No final newline
  * Copyright is just a string, no prefix field name
  * An empty line between these two

I think at least one of these is unintended.

**Comment by mxmehl** [comment] 2020-12-07 14:13
Thanks for the report.

The missing final newline may or may not be intended (@carmenbianca), but I wouldn't consider it a bug.

> Copyright is just a string, no prefix field name

In my tests with latest master, it always prints the SPDX tags in front, e.g. `SPDX-FileCopyrightText: 2020 Max Mehl <test@example.com>`. That's the expected behaviour. What's your output?

> An empty line between these two

That's intended and also how the tags in file headers would be added. This can be customised with templates though if you prefer a different style.

**Comment by kirelagin** [comment] 2020-12-18 01:33
The missing trailing newline is definitely a bug, because a `.license` file is intended to be a _text_ file and POSIX defines a text file as a file ending with a trailing newline. There is already #187 for this.

Regarding the other two I agree with @mxmehl.

**Comment by mxmehl** [comment] 2020-12-18 11:58
Oh, I didn't remember #187, thanks @kirelagin.

As the other two issues do not seem to be bugs, I'd close this issue to keep the tracker clean. Feel free to continue the discussion.

**Closed by mxmehl** 2020-12-18 11:58 UTC
