### ISSUE TITLE
Error from reuse 0.11.0 consuming a .rtf file

### ISSUE THREAD

**Issue by oddhack** [fsfe/reuse-tool#253] opened 2020-08-17 10:21 UTC
I have a .rtf file that's causing 'reuse lint' to throw an error attempting to parse it. However, the license information is entered in the file, and looks correct when viewing it in e.g. Libreoffice. While it's understandable that the REUSE tool would not read every possible documentation format, having it throw an error attempting to read .rtf suggests an underlying problem in whatever component consumes this type of file.

For ease of reproduction, I've created a minimal case repo here: https://github.com/oddhack/reuse-error . More information is in the repository README.md.

**Comment by oddhack** [comment] 2020-08-17 10:27
Also, it's apparently impossible to work around this with the .reuse/dep5 file - even if the license information is duplicated there, REUSE still tries and fails to read the .rtf file, and will not pass lint as a result. It *is* possible to put the license information into a .license file, so apparently the order of processing is .license -> file itself, if failed -> dep5, if not found in file. Is that true, and intentional?

**Comment by mxmehl** [comment] 2020-10-23 13:45
Yes, this is an ongoing issue. I'd close as duplicate of #246 however, where we discuss the problem of precedence. I do hope we can fix this soon.

**Closed by mxmehl** 2020-10-23 13:45 UTC
