### ISSUE TITLE
reuse should not add empty lines

### ISSUE THREAD

**Issue by jonasstein** [fsfe/reuse-tool#580] opened 2022-08-25 16:20 UTC
reuse should not add empty lines as line 2 in

```
# SPDX-FileCopyrightText: 2021 Jane Doe
#
# SPDX-License-Identifier: GPL-3.0-or-later

```

**Comment by mxmehl** [comment] 2022-08-26 10:30
Duplicate of #562

**Closed by mxmehl** 2022-08-26 10:30 UTC
Labels: duplicate
