### ISSUE TITLE
Feature: Support SVG metadata

### ISSUE THREAD

**Issue by niccokunzmann** [fsfe/reuse-tool#705] opened 2023-03-16 12:30 UTC
I would like REUSE to be able to detect the license in the SVG file that I edit with Inkscape.

![inkscape_minimized](https://user-images.githubusercontent.com/564768/225617162-cfe6eb69-5d84-43a1-86a0-ddac61bc31dd.svg)

```
  <!-- Copyright License -->
  <metadata
     id="metadata49">
    <rdf:RDF>
      <cc:Work
         rdf:about="etiquette-icon">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:creator>
          <cc:Agent>
            <dc:title>Andy Fitzsimon</dc:title>
          </cc:Agent>
        </dc:creator>
        <dc:rights>
          <cc:Agent>
            <dc:title>Andrew Michael Fitzsimon</dc:title>
          </cc:Agent>
        </dc:rights>
        <dc:publisher>
          <cc:Agent>
            <dc:title>Fitzsimon IT Consulting Pty Ltd</dc:title>
          </cc:Agent>
        </dc:publisher>
        <dc:identifier>http://andy.fitzsimon.com.au</dc:identifier>
        <dc:date>2006</dc:date>
        <cc:license
           rdf:resource="http://creativecommons.org/licenses/by-sa/3.0/" />
        <dc:title>Inkscape Logo</dc:title>
      </cc:Work>
      <cc:License
         rdf:about="http://creativecommons.org/licenses/by-sa/3.0/">
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#Reproduction" />
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#Distribution" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#Notice" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#Attribution" />
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#DerivativeWorks" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#ShareAlike" />
      </cc:License>
    </rdf:RDF>
  </metadata>
```

I wonder if this is in scope? I am new to the tool and maybe, I should use the XML/HTML license header from reuse.

**Comment by mxmehl** [comment] 2023-03-16 12:52
Thanks, but it's a duplicate of #367. In short: it's not in the scope and [there are good reasons for it](https://reuse.software/faq/#metadata) :)

**Closed by mxmehl** 2023-03-16 12:52 UTC
