### ISSUE TITLE
REUSE compliance and GitHub license integration

### ISSUE THREAD

**Issue by dominiksalvet** [fsfe/reuse-tool#84] opened 2019-08-30 13:01 UTC
With the release of [v0.4.0](https://github.com/fsfe/reuse-tool/releases/tag/v0.4.0), things have changed a lot. I would say that most changes are positive and it seems to me that a lot of program mechanisms are simpler as well as the [REUSE Specification](https://reuse.software/spec/), which is almost always good; things are almost never as simple as they should be. :black_circle: And license downloading... Good work on that! :+1: And I have hardly worked with the [v0.5.0](https://github.com/fsfe/reuse-tool/releases/tag/v0.5.0) so far, so I am looking forward. :smiley:

But there is a little problem arising from the new specification. It is the GitHub license integration. New specification requires all license files to be in the *LICENSES* directory, which makes sense to make things more simple and consistent but it certainly breaks the GitHub integration and it looks like the repository is not licensed at all at first glance. On the other hand, with previous versions there was a problem with the requirement of *LICENSE.txt.license* just to state the *LICENSE.txt* license identifier. I think it was the only way to both be REUSE compliant and meet GitHub integration (correct me if I am wrong). It certainly was not a perfect solution but it worked.

However, I like the idea that filename meets the license inside and REUSE should stick with it in my opinion. Nevertheless, I would like to open a discussion about any possible ways of GitHub integration and try to establish an official REUSE suggestion (or functionality) to solve this problem.

Personally, I don't have any specific suggestions but I have tried to somehow use both REUSE and GitHub integration in the [vhdldep](https://github.com/dominiksalvet/vhdldep) and [asus-fan-control](https://github.com/dominiksalvet/asus-fan-control) repositories.

In vhdldep, there was the preferred license added using GitHub website (the SPDX one is not recongised by GitHub :confused:) and that's it. In this case, it is good that all know that the preferred license is the MIT license. However, I don't know how to include this information in [README.md](https://github.com/dominiksalvet/vhdldep/blob/master/README.md), so I have omitted it so far. It could be confusing. At the end of the day, which MIT license (*LICENSE.txt*, or *LICENSES/MIT.txt*) is this project license under? *README.md* is far from legal text.

In asus-fan-control, the situation about the right interpretation of the license is much better. However, the integration of GitHub says 'Other' license, which is predictable...

So as you can see, it may be a minor problem but I really like this program and I would be really happy to solve the above problem. Do you have any ideas? Any possible solutions including adding a new functionality to the program? Thank you for your time and sharing your opinions! :tada:

**Comment by carmenbianca** [comment] 2019-08-30 14:08
I believe @mxmehl has been talking directly to GitHub to see if they could adapt to recognise the `LICENSES/` directory.

**Comment by amerlyq** [comment] 2019-09-15 00:33
I tried to workaround this by making symlink `LICENSE -> LICENSES/Apache-2.0.txt` but it's far from satisfying.
I have source code under Apache-2.0 but accompanying documentation/devnotes under CC-BY-SA-4.0, which makes whole combined distributed work somewhat covered by copyleft and still allows relicensing of the code part however user likes.

If GitHub will show project as whole as `Apache-2.0` it won't be true -- corporation can't simply download my repo and integrate into their firmware. But if GitHub will show it as `CC-BY-SA-4.0` it won't be right either -- because implementation part is still "free" and can be used in proprietary products, alas only after stripping all documentation.

So, I'm looking forward how this multilicense problem will be resolved by new integration with GitHub.

**Comment by alandtse** [comment] 2019-10-07 22:33
The issue is GitHub has a simplistic model with it's license display. It's better than what was there before, but is not designed to be as accurate as REUSE is supposed to be.  Ideally at some point in the future GitHub understands how to read REUSE to display the proper license.

@carmenbianca We discussed before at LLW that there should be probably a way for the tool to take a GitHub compliant repo and convert it to REUSE compliant (i.e., take the existing LICENSE file and then create REUSE necessary files and tag any files with that license that haven't been explicitly tagged otherwise). I think until GitHub converts, we should keep both the root License and the files in `LICENSES/`. I'm glad to see how much farther it's gotten since we last talked though. ;)  Given it's Hacktober, I may throw in a few PRs to help out.

**Comment by carmenbianca** [comment] 2019-10-24 11:16
Late response @alandtse 

I can see the appeal of it, but I'm not sure what the tool could be doing to facilitate that, or whether it should. The Spec in https://github.com/fsfe/reuse-docs/ also doesn't currently support the `LICENSE` file anymore.

It's totally possible, though, to create a `LICENSE` file nonetheless. It would be a duplicate and kind of unnecessary, but it's not impossible.

**Comment by alandtse** [comment] 2019-10-24 20:08
@carmenbianca I may be misreading it but the spec doesn't appear to prohibit the inclusion of a root LICENSE file. Agree though the issue is GitHub's in parsing it out. 

In truth, this is probably a place where [SPDX ](https://spdx.org/specifications)files should be generated by the reuse tool and left in the repo root and GitHub should read that. (Disclaimer, I'm involved in SPDX).

**Comment by mxmehl** [comment] 2020-02-05 20:03
I'll close this issue as it's not something the tool can provide (but have a look at the feature to [include REUSE as a Github action](https://reuse.software/dev/#ci)).

We are in communication with folks from Github and other source forges to provide a better integration. At the same time, we will think about a few modification that may lower the threshold potentially. Please join the [REUSE mailing list](https://lists.fsfe.org/mailman/listinfo/reuse) if you would like to participate.

**Closed by mxmehl** 2020-02-05 20:03 UTC
